#!/bin/sh
set -e

# prerm script for marine-lume
case "$1" in
    remove|upgrade|deconfigure)
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
